# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-25 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180223_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='imag',
            new_name='image',
        ),
    ]
