# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-02 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='应有尽有，货真价实', max_length=10, verbose_name='机构标签'),
        ),
    ]
