# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-26 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='learntime',
            field=models.IntegerField(default=0, verbose_name='学习时长（分钟数）'),
        ),
    ]
