# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-27 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180227_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_annoucements',
            field=models.CharField(default='', max_length=500, verbose_name='课程公告'),
        ),
    ]
