# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-26 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180226_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='name',
            new_name='user',
        ),
    ]
